#项目启动端口
server:
  port: 8083

#rft工作空间
polarion:
  txt: "C:/autoTest/workspace/RFTProject/Elevator_test_case（单梯）"

labview:
  #labview工作空间
  txt: "C:/autoTest/workspace/labProject/labviewWorkspace"
  #teststand启动命令
  cmd: "\"C:/Progra~2/National Instruments/TestStand 2016/Bin/SeqEdit.exe\" /runEntryPoint \"Single Pass\" "

#项目启动入口类
rft:
  #rft编译命令
  compile : "java -classpath \"C:/Progra~2/IBM/SDP/FunctionalTester/bin/rational_ft.jar\" com.rational.test.ft.rational_ft -datastore \"C:/jenkins/workspace/RFTProject/Elevator_test_case（单梯）\" -compile "
  #rft启动命令
  cmd: "java -classpath \"C:/Progra~2/IBM/SDP/FunctionalTester/bin/rational_ft.jar\" com.rational.test.ft.rational_ft -datastore \"C:/jenkins/workspace/RFTProject/Elevator_test_case（单梯）\" -rt.bring_up_logviewer false -playback Test1_Script1"

#autoTest配置信息
autoTest:
  username: "admin"
  password: "admin"
  httpLog: "{rft:'http://192.168.137.130:8081/job/logRFTProject/buildWithParameters',labview:'http://192.168.137.133:8081/job/logLabProject/buildWithParameters'}"